### ISSUE TITLE
Data is being dropped from Anchor claim reward transactions

### ISSUE THREAD

**Issue by kenzieschmoll** [Anchor-Protocol/anchor-web-app#102]
Originally filed at https://github.com/terra-project/finder/issues/70, but the issue may be on the Anchor side, so filing here also.

This is an example of claiming rewards from the Anchor Govern tab. Inspecting the transaction in Terra Finder shows that data is being dropped regarding the reward value. Looks like the entire from_contract event log is missing.
<img width="798" alt="Screen Shot 2021-04-22 at 6 49 54 AM" src="https://user-images.githubusercontent.com/43759233/115725806-05287b80-a337-11eb-956b-f07ea88555e1.png">
<img width="804" alt="Screen Shot 2021-04-22 at 6 48 06 AM" src="https://user-images.githubusercontent.com/43759233/115725947-1ffaf000-a337-11eb-8555-83f9391b0aab.png">

Here is an example of an Anchor claim reward tx that contains the data:
<img width="782" alt="Screen Shot 2021-04-22 at 6 46 20 AM" src="https://user-images.githubusercontent.com/43759233/115725263-8c292400-a336-11eb-820b-98b5cb1323b8.png">
<img width="692" alt="Screen Shot 2021-04-22 at 6 46 52 AM" src="https://user-images.githubusercontent.com/43759233/115725272-8d5a5100-a336-11eb-9250-5e83c1588be5.png">

This likely is not the right repo for this issue, as this seems like a data problem, so please transfer this issue to the proper repo if appropriate. Thank you.

**Comment by kjessec** [comment]
This is because the backend we're using for Finder (fcd) is dropping some of the logs from contract executions. Will escalate this internally and come back to you when fixed.

**Comment by kjessec** [comment]
Should be good now -- can you retry the same pages? There might be a cache in action so please do try a few times in a minute

**Comment by kjessec** [comment]
@kenzieschmoll I will look into this more thoroughly

**Comment by kjessec** [comment]
@kenzieschmoll is there a way I can get a hold of the problematic tx hash?

**Comment by kenzieschmoll** [comment]
Can I get your email to send it to you? I don't know if there are privacy concerns for posing here publicly.

**Comment by kjessec** [comment]
@kenzieschmoll jesse@terra.money. Thanks!
