### ISSUE TITLE
Getting this error code when trying to stake UST via a ledger Nano S

### ISSUE THREAD

**Issue by hugelynx** [Anchor-Protocol/anchor-web-app#104]
Error ID: 978663d564ba4d1e99ccb39a4477ca88
![anchor error](https://user-images.githubusercontent.com/83846274/117517099-d47d4e80-af92-11eb-8d4d-731977d4af75.jpg)

**Comment by iamssen** [comment]
@hugelynx Sorry for the inconvenience.

Unfortunally, I can't find the errors `978663d564ba4d1e99ccb39a4477ca88` and `827794e38a264ced839a8b46dcba689e` from our error report system (Sentry).

Could you send your wallet address (e.g. `terra12hnhh5...`) to my e-mail? ( ian@terra.money )

I will investigate your problem.

**Comment by hugelynx** [comment]
Hi

Good morning

Thanks for getting back to me

I've managed to get the transfer through, just needed some adjustments to
my ledger. My first time doing it but all sorted now.

Thanks again

**Comment by iamssen** [comment]
@hugelynx Great, thanks for the update! 😄

**Comment by hugelynx** [comment]
Hi

I do have one question, in the earn section do you know how I can increase
the APY from 20%? I've seen YouTube videos and seen ranges from 20-25%

Thanks

Paul

**Comment by OrmEmbaar** [comment]
@hugelynx I have the same issue. What adjustments did you need to make?

**Comment by hugelynx** [comment]
I didn't make any changes.

Don't really understand how this can be modified by the end user.

**Comment by OrmEmbaar** [comment]
Oh, odd. TerraStation was not initiating a request to my Ledger, but now it is. Thanks.
