### ISSUE TITLE
Showing same action twice

### ISSUE THREAD

**Issue by invis87** [Anchor-Protocol/anchor-web-app#108]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/228536/118147346-251ffc00-b418-11eb-8b28-ed16333f4794.png">

Transaction: https://finder.terra.money/tequila-0004/tx/313213C2FB063CEB52B22EC8039B96792383ACFF2528E685D517770FEEFE8E9D

**Comment by iamssen** [comment]
duplicated <https://github.com/Anchor-Protocol/anchor-web-app/issues/107>
