### ISSUE TITLE
Borrow limit > 100% view bug

### ISSUE THREAD

**Issue by invis87** [Anchor-Protocol/anchor-web-app#109]
This is kinda impossible on prod, but on testnet I catch it :D

<img width="796" alt="image" src="https://user-images.githubusercontent.com/228536/118494282-aa622400-b72a-11eb-886d-c3d612580412.png">

**Comment by kevinhankpark** [comment]
Hey invis97, this is not a bug, it is intended behavior. it's just that there are no liquidations being made on testnet right now!

**Comment by invis87** [comment]
@kevinhankpark I think UI is showing it in a wrong way. That why I call that "bug"

**Comment by kjessec** [comment]
@invis87 can you elaborate? it is intended to be shown like that, given that the bar should never go beyond 100% (if there are liquidations)

**Comment by invis87** [comment]
Hmmm, if it is intended, then probably all fine.
I just think it is ugly :) and looks like an "unexpected behavior":
<img width="232" alt="image" src="https://user-images.githubusercontent.com/228536/118632010-b2789d00-b7d8-11eb-8fdc-48fb280c4727.png">

**Comment by iamssen** [comment]
@invis87 Thanks for this report. I'll fix it on next update.
