### ISSUE TITLE
Unable to make repayment to loan

### ISSUE THREAD

**Issue by cmckenna07041992** [Anchor-Protocol/anchor-web-app#110]
<img width="742" alt="Screenshot 2021-05-19 at 14 15 19" src="https://user-images.githubusercontent.com/39618480/118818835-a8c06980-b8ac-11eb-9a24-3a23ea76b066.png">

Really important to get this fixed asap before people are liquidated.

**Comment by ACoopies** [comment]
Same error across the whole protocol... !!!

**Comment by kenzieschmoll** [comment]
Same here. I'm sure someone is on it already, but following this issue for updates. Thanks.

**Comment by kenzieschmoll** [comment]
@cmckenna07041992 @ACoopies if you check Terra Finder, the TX may still have gone through even though this error comes up.

**Comment by iamssen** [comment]
Sorry for the inconvenience. we are now fixing this problem. if the problem persists, please send an error id.

**Comment by CTJTFIT** [comment]
This morning we had multiple issues with the Anchor Protocol as the market was pulling back.  An overarching critical issue was the Anchor platform was not stable.  When accessing the platform, it would show data and then if we clicked to another tab it would be blank.   If you cannot access the account data to act on it is like watching helplessly from the sidelines knowing there was the ability to prevent any issues.  

Two other critical issues that occurred that resulted in unnecessary losses on two of three accounts are  1) not being able to claim rewards in real time and convert to UST and 2) not being able to use available UST in the wallet to pay down the outstanding balance in real time.  

For almost an hour when trying to claim rewards to convert to UST the available ANC rewards disappeared altogether.  We went to claim rewards between 9:00am and 9:21am est and the system kept giving an "Operation TimeOut" error message. 
 Then at 9:21 the available rewards to claim disappeared from the system.  Originally this showed it happened with the Latest Block listed as 3026753 (see the screenshot).  Then the system just kept not showing data after disconnecting and reconnecting the wallet and showed the Latest Block: 0.   The rewards did not show back up until 10:12am EST. 

![Avaliable rewards disappeared at 9:21am est](https://user-images.githubusercontent.com/84463101/118845561-e1a31300-b899-11eb-8211-f1db49fbb043.png)

Additionally, when trying to use the repay button the transactions kept not processing.  The system would not respond or the Failed to Broadcast error messages occurred repeatedly. 

Ultimately to have accounts being liquidated from not being able to access the system is not a viable option.  We are huge fans of Luna but today was a massive disappointment in the ability to rely on the Anchor Protocol when it mattered most.  We are okay being responsible for managing the risk of leverage.  What we are not able to take on and manage is the technology risk of the platform.  Given the volume of transactions and value in the platform users must be able to count on being able to access the platform to manage the risk of liquidation properly.  Having this blocked by limitations of the platform is not feasible.  

Please let us know if we can assist in sharing more to help resolve the issues going forward.

Thank you for your work on the project.
