### ISSUE TITLE
Unable to borrow

### ISSUE THREAD

**Issue by hugelynx** [Anchor-Protocol/anchor-web-app#113]
I've attempted to borrow as a test but keep getting this error code

Error ID: 162b1b1dff3e4513848d073f7d6e0821

I'm connecting via my Nano S Ledger which has been fine with Terra Station

**Comment by hugelynx** [comment]
![anchor borrow error](https://user-images.githubusercontent.com/83846274/119031001-7f820500-b9a2-11eb-8cae-061cc9c969a6.jpg)

**Comment by iamssen** [comment]
@hugelynx The error seems to be Ledger's error message. I'm sorry, but I don't think I can give you any guidance. Please try again after disconnecting Ledger.

<https://www.google.com/search?q=ledger+nano+%22Unknown+status+code%3A+28161%22&newwindow=1&sxsrf=ALeKk02Fn50Duw6y2sQanE9NeEUUA9H0xg%3A1621566617046&ei=mSSnYMu2Aoj70ATZ8B0&oq=ledger+nano+%22Unknown+status+code%3A+28161%22&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABMgUIIRCgAVD5Qlj6VGCWV2gBcAB4AIABvAGIAY0EkgEDMC40mAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=gws-wiz&ved=0ahUKEwiL58Cx5tnwAhWIPZQKHVl4BwAQ4dUDCA4&uact=5>
