### ISSUE TITLE
Where can Anchor loan liquidation transactions be found?

### ISSUE THREAD

**Issue by kenzieschmoll** [Anchor-Protocol/anchor-web-app#116]
These transactions and their respective data (amount of bLuna liquidated, timestamp, amount of loan payed down, etc.) are important for calculating taxable gains/losses. As far as I can tell, these transactions are not surfaced in terra finder. Where is this data, and how can the end user view it? thanks.

**Comment by iamssen** [comment]
@kenzieschmoll <https://finder.terra.money/columbus-4/address/terra1tmnqgvg567ypvsvk6rwsga3srp7e3lg6u0elp8>

You can check it using the "liquidate_collateral" msg in the overseer contract above.

Also, our backend developer is making an API related to this. 

Thank you.

**Comment by kenzieschmoll** [comment]
Thanks. Do you have an expected time that the API for liquidation information will be available? Is there a place where Anchor API endpoints are documented?

**Comment by kjessec** [comment]
Hey @kenzieschmoll, Currently we are in the process of migrating our backend while also implementing the endpoint you mentioned too. (it'll be served in the form of full transaction history with better granularity with "got liquidated" entry as well).

We're targeting mid June for all these!
