### ISSUE TITLE
Feat. Req.: Enable browser notifications for liquidation warnings/notifications

### ISSUE THREAD

**Issue by Chinoman10** [Anchor-Protocol/anchor-web-app#119]
Hi there,
Following [a conversation on Discord](https://ptb.discord.com/channels/816973230526693396/816973230979153931/846742188666388500), I feel like adding browser notifications to users who are about to be liquidated (LTV>40 or 45%) or when they are liquidated would be a very _nice-to-have_ feature. Provided of course that they have a tab open with the Anchor web app to ensure that the app running locally is updated in real-time.
While it's possible that the future mobile app will feature such functionalities, adding more to the web one would be great regardless.

**Comment by iamssen** [comment]
@Chinoman10 I think it's an interesting feature.

We are currently focusing on features for mobile web support. After completing it, I will discuss your feature request with my team members.

Thank you.

**Comment by Chinoman10** [comment]
I guess this was released just now and the issue can be closed @iamssen ?

**Comment by iamssen** [comment]
@Chinoman10 Yes! this feature released. thanks!

**Comment by iamssen** [comment]
This notification feature is a temporary release. Our backend developers are preparing for server push now, so we can provide better service soon. 😄
