### ISSUE TITLE
Feat. Req.: Local currency conversion (display only)

### ISSUE THREAD

**Issue by Chinoman10** [Anchor-Protocol/anchor-web-app#135]
Suggestion that came in [on Discord](https://ptb.discord.com/channels/816973230526693396/821639657485500416/849809061544460377):
The same way that we can see how much our UST is worth in the local currency (EURO/EUT, etc.) inside Terra Station, display the same kind of feature on the Anchor Web App, so we can see how much our deposits, collaterals, etc. are worth.

**Comment by iamssen** [comment]
@Chinoman10 I sent this issue to our service planning team. 

I'll let you know when I get their answer.

Thanks!

**Comment by kevinhankpark** [comment]
@Chinoman10 ,

Thanks for the suggestion, but as of now this is a feature that we are not considering to develop, given our development plans. Since the market is in UST, we are only considering USD as denominations at the moment. 

Thanks again!
