### ISSUE TITLE
Error on testnet claim rewards

### ISSUE THREAD

**Issue by RPM718** [Anchor-Protocol/anchor-web-app#141]
![error claim rewards](https://user-images.githubusercontent.com/86089086/122496927-92e0ba00-cfba-11eb-9ace-e7df63d0accc.PNG)

hello. probably this never happen, but sometimes could. this happen in testnet. the claim reward show this error and dont let me claimed. i dont know if could be the amount of reward. there is any support for testnet for things like this?.

regards.

**Comment by iamssen** [comment]
@RPM718 We executed the testnet poll to readjust the emission cap.

<https://app.anchorprotocol.com/gov/poll/69> (only visible on testnet)

Please check if the problem has been solved.
