### ISSUE TITLE
Testnet Borrow Failing

### ISSUE THREAD

**Issue by konraddroeske** [Anchor-Protocol/anchor-web-app#151]
Havne't heard back from anyone on the discord, so just posting this here...

![test-net-error](https://user-images.githubusercontent.com/51546277/125176532-367c4f00-e1a2-11eb-9030-ad80a7c5b5ad.png)

Only Borrow fn seems to have this issue:

The transaction requested has failed due to the following reason:
generic: contract query failed: generic: Price is too old:

Here is the tx for reference:

https://finder.terra.money/tequila-0004/tx/A0154E36CB844F4793D8EDD52EA4DDCFE6D41B576B4BF4431E4B42BEE568E7B4

**Comment by iamssen** [comment]
@konraddroeske I will check.

**Comment by kjessec** [comment]
Hey @konraddroeske looks as if our testnet infra tasks are malfunctioning. Checking now

**Comment by kjessec** [comment]
Should be up now.
