### ISSUE TITLE
Create and/or document a REST API for interacting with Anchor data

### ISSUE THREAD

**Issue by kenzieschmoll** [Anchor-Protocol/anchor-web-app#155]
Is there an existing REST API to find data like 20% yield earn balance, bLuna balance, collateral balance, borrowed balance, borrowing rewards balance, etc? If there is, is it documented anywhere?

**Comment by iamssen** [comment]
There is no REST API to obtain calculated values. WebApp is calculating low-level data from Contract.

All Contract Query / formulas for WebApp are [here](https://github.com/Anchor-Protocol/anchor-web-app/tree/feature/beth/app/src/%40anchor-protocol/webapp-fns), but there are no documents yet, and they are not convenient APIs for external developers.

You should still refer to docs.anchorprotocol.com.

<https://docs.anchorprotocol.com/smart-contracts/deployed-contracts>

**Comment by iamssen** [comment]
Also refer to this repo that I recently started

https://github.com/Anchor-Protocol/anchor-notebooks
