### ISSUE TITLE
Cannot withdraw ust in anchor protocol using math wallet

### ISSUE THREAD

**Issue by infinite-donn** [Anchor-Protocol/anchor-web-app#160]
Dear team, i cant withdraw my ust on anchor protocol , im using MathWallet, can u help me to solve this ? This is my error id 79d373dfbf8a49cb96323ae05917819e

**Comment by iamssen** [comment]
@infinite-donn Please try again via terra station extension or terra station mobile. There's nothing we can do for you if it's just a matter of math wallet.

**Comment by infinite-donn** [comment]
Thx to replied me , i try To recover my Terra wallet to Terra Station mobile , but Mnemonic phrase in Terra is 24 , otherwise math wallet only 12

**Comment by iamssen** [comment]
@infinite-donn I'm sorry. I can't solve the problems in Math wallet. For issues such as "How do I move the terra wallet from the matn wallet to the terra station?" or "The tx sign of the matn wallet is not working properly" you should contact the matn wallet.
