### ISSUE TITLE
Error initializing Apollo GraphQL project "Unnamed Project"

### ISSUE THREAD

**Issue by 0xWWW** [Anchor-Protocol/anchor-web-app#192]
![Screen Shot 2021-11-22 at 11 29 03 AM](https://user-images.githubusercontent.com/50073310/142792232-9c3314b8-0413-49c8-b8fd-5bb3f08408b4.png)

Getting error with `yarn graphql:download-schema`. Also looks `https://tequila-mantle.anchorprotocol.com\` is out of date because currently `tequila-mantle` wasn't supported more.

**Comment by iamssen** [comment]
@0xWWW Thanks for the issue. I just updated on this. https://github.com/Anchor-Protocol/anchor-web-app/commit/df84d4c309ddf6ff2180f6b9a175dae23b4814dd
