### ISSUE TITLE
How to run web app

### ISSUE THREAD

**Issue by generaltso518** [Anchor-Protocol/anchor-web-app#193]
Is there a guide how to actually get this running? for example do we use pm2, what is the node file to start, what are nginx config settings

**Comment by iamssen** [comment]
This is not a node application. just run `yarn run app:build`. you can get the static files such as js and html

**Comment by generaltso518** [comment]
Thank you, after running I get these files in app
build         scripts        tsconfig.script.json        vite.config.ts
index.html    script.sh      vercel-build-ignore.sh
package.json  src            vercel-ignore-storybook.sh
public        tsconfig.json  vercel.json


and these in app/build
assets  favicon.ico  fetchWorker.js  logo.png  manifest.json  robots.txt

the index.html file really does not have anything except wallet connect

what is the correct root path for /etc/nginx/sites-available/default  server {
   listen 80 default_server;
   root /var/www/anchor-web-app/app/build;
   server_name [your.domain.com] [your other domain if you want to];
   index index.html index.htm;
   location / {
   }
}

**Comment by generaltso518** [comment]
here is my nginx config but still doesn't work
```
server {
   listen 80 default_server;
   root /var/www/anchor-web-app/app;
   server_name app.example.com;
   index index.html index.htm;
   location / {
   }

	location /src/ { 
	   autoindex on;
	   root /var/www/anchor-web-app/app;
	}

	location /public/ { 
	   autoindex on;
	   root /var/www/anchor-web-app/public;
	}

	location /build/ { 
	   autoindex on;
	   root /var/www/anchor-web-app/build;
	}
}
server {
   listen *:443 ssl;
   root /var/www/anchor-web-app/app;
   server_name app.example.com;
   ssl_certificate /etc/ssl/localhost+1.pem; 
   ssl_certificate_key /etc/ssl/localhost+1-key.pem;
}
```

**Comment by sayveprotocol** [comment]
ok the files end up being in app/build
the reason I couldn't see it before was the build kept failing due to node memory issues so this solves it
```
export NODE_OPTIONS=--max_old_space_size=4096
```
So to correctly build
```
cd anchor-web-app && export NODE_OPTIONS=--max_old_space_size=4096 && yarn install && yarn run app:build
```
Then static files are in 
```
anchor-web-app/app/build/
```

**Comment by generaltso518** [comment]
ok the files end up being in app/build
the reason I couldn't see it before was the build kept failing due to node memory issues so this solves it

```
export NODE_OPTIONS=--max_old_space_size=4096
```
So to correctly build
```
cd anchor-web-app && export NODE_OPTIONS=--max_old_space_size=4096 && yarn install && yarn run app:build
```
Then static files are in
```
anchor-web-app/app/build/
```
