### ISSUE TITLE
Anchor Protocol Missing Liquidity

### ISSUE THREAD

**Issue by gfb1967** [Anchor-Protocol/anchor-web-app#211]
Hello,

I executed below transaction: 
Tx 81E21D2EC5499F678986BABC25019025219F3E8E12F8EC683AFAD810DD27CD3C
to the Anchor Liquidity Pool today at 1:13 eastern time.

The liquidity appeared in Anchor Protocol as a pool balance as expected. Later today when I checked the pool balance it was $0.00. There is no record of a withdrawal transaction or trace of the funds that I can find.

Please assist if possible-
Thank you!

**Comment by iamssen** [comment]
@gfb1967 Please check this banner

![image](https://user-images.githubusercontent.com/357619/148884064-f7924420-e408-4872-a1c1-94afb2eab7c4.png)

**Comment by gfb1967** [comment]
Thank you very much!
