### ISSUE TITLE
Web App Failing Out the Box

### ISSUE THREAD

**Issue by abishr12** [Anchor-Protocol/anchor-web-app#217]
Running `yarn install` after clone gives me

error An unexpected error occurred: "Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in /Users/Adham1/Desktop/repos/anchor-web-app/yarn.lock

![Screen Shot 2022-01-25 at 8 37 37 PM](https://user-images.githubusercontent.com/20959266/151105141-f9da8dfb-1636-4a6c-8f2c-b9e119170804.png)

Tried deleting the yarn.lock, reinstalling packages, and then ran `yarn run app:start`
and got (yes i tried running yarn install again)

```
Internal Error: root-workspace-0b6124@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
```

![Screen Shot 2022-01-25 at 8 41 34 PM](https://user-images.githubusercontent.com/20959266/151105143-a41dc5df-f582-4edc-9b37-147385026c87.png)

Please help

**Comment by lopezj19** [comment]
Hello @abishr12    , A support ticket has been opened for you with Support ticket number TM5366. You should talk to an ANHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by cosullivan** [comment]
Can you confirm if you are still getting this with the latest commits in master?
