### ISSUE TITLE
Clarify used timezone on the proposals End Time

### ISSUE THREAD

**Issue by silvermind** [Anchor-Protocol/anchor-web-app#234]
Would be nice to see the End Time with the Zimezone included, currently it's not clear if it's converted using the bowser time zone or is in UTC.

e.g. https://app.anchorprotocol.com/poll/15

Also would it be possible to show the actual execution date using the current config param?

**Comment by cosullivan** [comment]
Both of these have been address now and will be available on mainnet soon.

![image](https://user-images.githubusercontent.com/2428335/163120094-6d154844-387f-4fa4-b8d1-9849d2fdef66.png)
