### ISSUE TITLE
Earn Funds Didn't Arrive

### ISSUE THREAD

**Issue by DaveHH2574** [Anchor-Protocol/anchor-web-app#291]
The transaction shows success but the funds didn't arrive but they have been pulled from my account.
![2022-03-24](https://user-images.githubusercontent.com/102326189/160001654-5c10247e-4053-48cd-9fe3-c43587eb8bdd.png)
![2022-03-24 (3)](https://user-images.githubusercontent.com/102326189/160001659-0162b77e-4157-4ebc-ac2a-ccc5c89f9963.png)
![2022-03-24 (2)](https://user-images.githubusercontent.com/102326189/160001661-bebb6f63-d98b-48f4-b2bb-f1e0071ec878.png)
![2022-03-24 (1)](https://user-images.githubusercontent.com/102326189/160001664-eadfef28-9157-4201-a7ab-3ef1a993d288.png)

**Comment by cosullivan** [comment]
Hi,

Please raise this as a support request on the Discord channel and someone will help you out.

The Discord channel is linked on the bottom of the main Anchor website.

Thanks.
