### ISSUE TITLE
Missing 26k Deposit

### ISSUE THREAD

**Issue by TommyB78** [Anchor-Protocol/anchor-web-app#296]
I made two deposits into my anchor however I can only see the first one in MyPage value amount not the second. I should see $55,800 but it shows $29,300

Missing -$26,568.995524
https://finder.terra.money/columbus-5/tx/D019D3427F27A077E3A8DFA148C38A96D35B9A63FD5EFBB1017AB970EE0A73D8

Deposited-$29,235.930217 
https://finder.terra.money/columbus-5/tx/BE794A453B658D9A4B01726928C07E8C306AEF034ADDD173A4E86F8F6A2C69AB

Metamask wallet - 0x7056e80AA20660559b95E3894C0361a183E2Be59

**Comment by cosullivan** [comment]
Hi, 

Please raise this as a support request on the Discord channel and someone will help you out.

The Discord channel is linked on the bottom of the main Anchor website.

Thanks.
