### ISSUE TITLE
Staking error 

### ISSUE THREAD

**Issue by wingut** [Anchor-Protocol/anchor-web-app#310]
Hi, I tried to stake and it said transaction failed and told me to come here and provide the TX hash so if you could help me figure this out I would truly appreciate it, thanks
Tx hash CA1DA2FDEBCF08A0C7EEF4996898E7F8CEA127B063C56EFFC78EA257842B4293

**Comment by cosullivan** [comment]
Hi, 

Please post questions regarding support to the Discord channel. 

The link is available on the Website.

Thanks, Cain.

**Comment by Molly150** [comment]
> Hi, I tried to stake and it said transaction failed and told me to come here and provide the TX hash so if you could help me figure this out I would truly appreciate it, thanks Tx hash CA1DA2FDEBCF08A0C7EEF4996898E7F8CEA127B063C56EFFC78EA257842B4293

Hello, A support ticket has been opened for you with Support ticket number TM7639. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)
