### ISSUE TITLE
Modify Collateral Attribute fails to get staked governance Anchor

### ISSUE THREAD

**Issue by frozencode** [Anchor-Protocol/anchor-web-app#312]
When using the Anchor UI to make a proposal to raise bETH LTV to 75% UI is unable to retreive query for vested Anchor tokens.

Troubleshooting steps taken:

Disconnected + reconnected wallet
restarted browser (chromium)
used different browser (safari ios, chromium android)
used different wallet (failed to repr
<img width="1440" alt="Screen Shot 2022-04-02 at 12 05 44 AM" src="https://user-images.githubusercontent.com/7212523/161367355-b8d46f93-7182-4277-a300-d1b33b134d37.png">
oduce)

**Comment by cosullivan** [comment]
This is as expected if your account doesn't have any ANC tokens vesting. 

You can navigate to the vesting claim URL directly to confirm.
https://app.anchorprotocol.com/anc/vesting/claim

**Comment by Watson199** [comment]
> When using the Anchor UI to make a proposal to raise bETH LTV to 75% UI is unable to retreive query for vested Anchor tokens.
> 
> Troubleshooting steps taken:
> 
> Disconnected + reconnected wallet restarted browser (chromium) used different browser (safari ios, chromium android) used different wallet (failed to repr <img alt="Screen Shot 2022-04-02 at 12 05 44 AM" width="1440" src="https://user-images.githubusercontent.com/7212523/161367355-b8d46f93-7182-4277-a300-d1b33b134d37.png"> oduce)

Hello, A support ticket has been opened for you with Support ticket number TM2947. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by frozencode** [comment]
> This is as expected if your account doesn't have any ANC tokens vesting.
> 
> You can navigate to the vesting claim URL directly to confirm. https://app.anchorprotocol.com/anc/vesting/claim

I have confirmed I have no tokens in vesting contract. I have 1,000 tokens staked in Anchor governance as seen here:
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/7212523/161387929-e397ab9b-4e98-4844-8512-0adb4b80d4ac.png">

so it's not a query error then the page is just nor recognizing my governance stake?

**Comment by cosullivan** [comment]
To create a poll, you need to have 1,000 ANC in your wallet whereas when you vote on a poll you can only vote with the ANC that you have staked.

The page queries the vesting contract to determine whether you have any ANC tokens that are available to claim, so it does this indepenantly of a poll, ie, it will do this on the main page too.

**Comment by frozencode** [comment]
> To create a poll, you need to have 1,000 ANC in your wallet whereas when you vote on a poll you can only vote with the ANC that you have staked.
> 
> The page queries the vesting contract to determine whether you have any ANC tokens that are available to claim, so it does this indepenantly of a poll, ie, it will do this on the main page too.

Just changed title to reflect actual issue. I have the anchor staked in governance, however, it does not allow for me to post the proposal since the ui botton is greyed out and the deposit section is red. checking for the anchor it does report I have it in governance in the image above, I'm checking the messages sent to see if something is awry when querying for my staked anchor but I cant see whats wrong.

**Comment by mauver** [comment]
No staking ANC, unstake your ANC and create the poll.

**Comment by frozencode** [comment]
YEP YOUR RIGHT I'M AN IDIOT - ISSUE CLOSED
