### ISSUE TITLE
avax borrow

### ISSUE THREAD

**Issue by Nlawre08** [Anchor-Protocol/anchor-web-app#318]
my last 2 trasnsactions say it gone through but i havnt recieved ust and it says i know owe it in the borrow page

**Comment by Watson199** [comment]
> my last 2 trasnsactions say it gone through but i havnt recieved ust and it says i know owe it in the borrow page

Hello, A support ticket has been opened for you with Support ticket number TB82836HH. You should talk to an ANHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by cosullivan** [comment]
Please raise this issue in the Discord channel which you can find a link to from the main website.

**Comment by Molly150** [comment]
> my last 2 trasnsactions say it gone through but i havnt recieved ust and it says i know owe it in the borrow page

Hello, A support ticket has been opened for you with Support ticket number TM7839. You should talk to an ANCHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)
