### ISSUE TITLE
Funds not arriving in Anchor Earn wallet

### ISSUE THREAD

**Issue by Clinton4552** [Anchor-Protocol/anchor-web-app#319]
I was depositing UST on the from my Metamask (Avalanche) this morning and the funds have left my wallet but not arrived in the Anchor earn wallet, looking at the log in Anchor it indicates it succeeded but these are not showing and I am unsure how to trace or identify the issue.

**Comment by jhonatansuarez** [comment]
@Clinton4552 .Same just happen to me .

**Comment by Clinton4552** [comment]
@jhonatansuarez this has now corrected, Basically I had to do a transaction restore process in the Anchor protocol. To do this I went into my metamask wallet, found the activity related to the deposit, opened the Deposit Stable activity, then selected "view on block explorer", copied the "Transaction Hash" number, then went back to the Anchor protocol, clicked on my wallet address at top right hand corner, selected "Restore Transaction", pasted the Transaction Hash number into the dialog box, selected "Restore". this prompted an acceptance in Metamask, which i accepted, and once that completed and I refreshed Anchor page, my funds appeared in my Earn wallet.

**Comment by Watson199** [comment]
> I was depositing UST on the from my Metamask (Avalanche) this morning and the funds have left my wallet but not arrived in the Anchor earn wallet, looking at the log in Anchor it indicates it succeeded but these are not showing and I am unsure how to trace or identify the issue.

Hello, A support ticket has been opened for you with Support ticket number TB9936HH. You should talk to an ANHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by Watson199** [comment]
> @Clinton4552 .Same just happen to me .

Hello, A support ticket has been opened for you with Support ticket number TB10036HH. You should talk to an ANHOR PROTOCOL Dev on the [LIVE SUPPORT PAGE](https://forumanchorprotocol.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://forumanchorprotocol.net/)

**Comment by jhonatansuarez** [comment]
@Clinton4552 thank you very much for your help , well done .

**Comment by StevenLo-11** [comment]
> @jhonatansuarez this has now corrected, Basically I had to do a transaction restore process in the Anchor protocol. To do this I went into my metamask wallet, found the activity related to the deposit, opened the Deposit Stable activity, then selected "view on block explorer", copied the "Transaction Hash" number, then went back to the Anchor protocol, clicked on my wallet address at top right hand corner, selected "Restore Transaction", pasted the Transaction Hash number into the dialog box, selected "Restore". this prompted an acceptance in Metamask, which i accepted, and once that completed and I refreshed Anchor page, my funds appeared in my Earn wallet.

I did the same thing but this is what I received.
![Screen Shot 2022-04-07 at 5 35 21 PM](https://user-images.githubusercontent.com/78856352/162330619-373486c8-8a04-42f6-baa1-3ed7d2bec445.png)

**Comment by yunanni** [comment]
You have to synchronize your wallet and debug it

**Comment by Station-Dev** [comment]
> I was depositing UST on the from my Metamask (Avalanche) this morning and the funds have left my wallet but not arrived in the Anchor earn wallet, looking at the log in Anchor it indicates it succeeded but these are not showing and I am unsure how to trace or identify the issue.

Hello @, A support ticket has been opened for you. Talk to a Anchor Protocol Dev on the support live chat at [Live support page](https://anchorforums.com/) . We believe your case will be resolved as soon as possible. [CLICK HERE](https://anchorforums.com/)

**Comment by yunanni** [comment]
You only need to synchronize your wallet and then you debug it.. you don’t
need any support

**Comment by Charlotte61** [comment]
> I was depositing UST on the from my Metamask (Avalanche) this morning and the funds have left my wallet but not arrived in the Anchor earn wallet, looking at the log in Anchor it indicates it succeeded but these are not showing and I am unsure how to trace or identify the issue.

Hello, Kindly chat with one of our support agent on live chat with ticket number TB2923HH to get a quicker response [CLICK HERE](https://forumanchorprotocol.net/).

**Comment by yunanni** [comment]
Don’t chat with any support it is a scam.. big scam .. you can do it
yourself .. you just need to synchronize your wallet and then you debug
it.. I can send you the url to get it done
