### ISSUE TITLE
UST borrowing confirmed but not showing in Anchor

### ISSUE THREAD

**Issue by jf518** [Anchor-Protocol/anchor-web-app#324]
I borrowed UST on AVAX. Snowtrace shows the transaction as confirmed, but the funds are not showing up as borrowed on Anchor. When I restore the transaction I get the following message: 

Oops, something went wrong!

Outgoing sequence expected.

Can someone please help? 

Thanks!!!

**Comment by Station-Dev** [comment]
Hello @, A support ticket has been opened for you. Talk to a Anchor Protocol Dev on the support live chat at [Live support page](https://anchorforums.com/) . We believe your case will be resolved as soon as possible. [CLICK HERE](https://anchorforums.com/)

**Comment by steward833** [comment]
> I borrowed UST on AVAX. Snowtrace shows the transaction as confirmed, but the funds are not showing up as borrowed on Anchor. When I restore the transaction I get the following message:
> 
> Oops, something went wrong!
> 
> Outgoing sequence expected.
> 
> Can someone please help?
> 
> Thanks!!!

Hello, Kindly chat with one of our support agent on live chat to get a quicker response [CLICK HERE](https://forumanchorprotocol.net/).

**Comment by jf518** [comment]
> > I borrowed UST on AVAX. Snowtrace shows the transaction as confirmed, but the funds are not showing up as borrowed on Anchor. When I restore the transaction I get the following message:
> > Oops, something went wrong!
> > Outgoing sequence expected.
> > Can someone please help?
> > Thanks!!!
> 
> Hello, Kindly chat with one of our support agent on live chat to get a quicker response [CLICK HERE](https://forumanchorprotocol.net/).

Hi - I resolved this issue so this should closed out. Thanks!
