### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by jerrys1142** [Anchor-Protocol/anchor-web-app#345]
The transaction requested has failed due to the following reason:
: 4772757uusd is smaller than 500000000uusd: insufficient funds
•	Tx Hash[3063D3...757E5](https://finder.terra.money/columbus-5/tx/3063D35D770B7228D7707D8BAD0B57671C8E92030BCBD1BF1749FFDDC8757E51)

**Comment by cosullivan** [comment]
Please raise this on the discord, links are available from the main website.
