### ISSUE TITLE
getting CORS origin issue

### ISSUE THREAD

**Issue by prasathmani** [Anchor-Protocol/anchor-web-app#77]
It was working earlier, now I'm getting cross origin request blocked error
![image](https://user-images.githubusercontent.com/11345598/113371331-b153f380-9383-11eb-8514-951e6b990c4e.png)

**Comment by iamssen** [comment]
@prasathmani `https://tequila-mantle.anchorprotocol.com` is the development server (Testnet). 

Could you check your network setting? change the network to "Mainnet"

![image](https://user-images.githubusercontent.com/357619/113372855-8af28000-93a4-11eb-8c1c-636eded0674f.png)

**Comment by prasathmani** [comment]
Testnet is working now, thanks
