### ISSUE TITLE
No memo field in anchor app wallet send modal

### ISSUE THREAD

**Issue by martinyung** [Anchor-Protocol/anchor-web-app#82]
In the [discord](https://discord.com/channels/464241079042965516/464241079042965518/828933396667301988) channel, i realise some user did not put in the memo when sending to wallet in exchanges. One of the reason is because there is no `memo` field in the anchor app wallet send modal

<img width="660" alt="wallet-send-modal" src="https://user-images.githubusercontent.com/8136256/113725900-5d9c2e00-9726-11eb-88d2-7a45a152c059.png">

in the MIR wallet, there is no memo field too but there is a warning saying `Double check if the above transaction requires a memo`.

I would like to discuss here whether this is already in the roadmap or is there any reason why the `memo` field is not present?

I would love to contribute to the fix once we have a conclusion on the solution. thank you

**Comment by iamssen** [comment]
@martinyung Thanks for the report.

![image](https://user-images.githubusercontent.com/357619/113832295-70187500-97c3-11eb-8b39-5fc60ec42b4c.png)

I added the memo field on the send dialog.

and when you send without memo you can see this confirm dialog.

<https://anchor-web-app-git-feature-send-memo-anchor-protocol.vercel.app/earn>

**Comment by martinyung** [comment]
thanks alot @iamssen, this will greatly help people new to crypto.
