### ISSUE TITLE
Add back the Interest Earned section

### ISSUE THREAD

**Issue by RomainLanz** [Anchor-Protocol/anchor-web-app#89]
Hey there! 👋 

Since we do not have access to your Trello Board, we do not know the reason why the `Interest Earned` section has been removed from the UI (code is still there).

Commit: https://github.com/Anchor-Protocol/anchor-web-app/commit/becc666adc250f9df04f511ce24c7113128ff433

I believe it can still be useful to display this information as a note, like it has been done with the liquidation price of bLuna (https://github.com/Anchor-Protocol/anchor-web-app/commit/84e03f7e2265946a31f4da431e4332268b10eb67 & https://github.com/Anchor-Protocol/anchor-web-app/commit/3f388528f2a99c08faae2cad2533e6644648342c).

**Comment by iamssen** [comment]
Sorry for the inconvenience. I will write more details the commit messages.

And the restoring "Interest Earned" section issue I need to more checking to the backend development. I will update after this issue checked.

**Comment by kjessec** [comment]
the indexer for interest earned is being re-built from scratch. will be a feature in a near future. Thanks!

**Comment by luigi311** [comment]
Thanks! Safe to assume this will be able to backtrack how much was earned throughout the entire history of the terra wallet?

**Comment by davordavidovic** [comment]
Hey curious to know what the status of this is? I think it's a much needed feature :)

**Comment by kjessec** [comment]
This would need support from the backend -- logic wise it's kind of complicated and we're working towards this, although the priority is somewhat low due to col-5 migration. Please give us some more time 🙏  Thanks!

**Comment by RomainLanz** [comment]
100% normal, Columbus-5 update is far more important than this. 😄 

Will it be possible to have the interest retroactively to this day, or will it start from scratch?
